# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: mongo
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: mongo
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mongo
        tier: database
    spec:
      containers:
        - image: mongo:latest # image from docker-hub
          name: mongo

          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
            - name: mongo-persistent-storage
              mountPath: /var/lib/mongo #This is the path in the container on which the mounting will take place.
      volumes:
        - name: mongo-persistent-storage # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: mongo-pv-claim
---
# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mongo  # DNS name
  labels:
    app: mongo
    tier: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:       # mysql Pod Should contain same labels
    app: mongo
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant