version: '1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - shared-network
    volumes:
      - ./mongo-db:/var/lib/mongo/data
  
  script:
    container_name: script
    restart: on-failure
    build: 
      dockerfile: Dockerfile
    image: script-task
    networks:
      - shared-network
    depends_on:
      - mongo

networks:
  shared-network: